#:schema node_modules/wrangler/config-schema.json
name = "darbare"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "darbare-db"
database_id = "34316755-3710-4189-bb2f-e77a79a39fb8"
migrations_dir = "drizzle"